@startuml name
struct SwGeometryPushConstants {
    + mSceneVertexBuffer: vk::DeviceAddress
    + mSceneMaterialConstantsBuffer: vk::DeviceAddress
    + mSceneNodeTransformsBuffer: vk::DeviceAddress
    + mSceneInstancesBuffer: vk::DeviceAddress
    + mSceneVisibleRenderItemsBuffer: vk::DeviceAddress
    + mSceneVisibleRenderInstancesInstanceIndexBuffer: vk::DeviceAddress
}

struct SwSceneFlags {
    + mAssetLoadedFlag: bool
    + mAssetUnloadedFlag: bool
    + mInstanceLoadedFlag: bool
    + mInstanceUnloadedFlag: bool
    + mReloadMainBufferFlag: bool
}

class SwScene {
    + mFlags: SwSceneFlags
    - mCamera: SwCamera
    - mAssets: std::unordered_map<std::filesystem::path, SwAsset>
    - mPasses: std::unordered_map<SwPassType, SwPass&>
    - mRenderGraph: SwRenderGraph
    - mOpaqueBatches: std::unordered_map<std::uint32_t, SwBatch>
    - mMaskBatches: std::unordered_map<std::uint32_t, SwBatch>
    - mTransparentBatches: std::unordered_map<std::uint32_t, SwBatch>
    - mGeometryPushConstants: SwGeometryPushConstants
    - mSceneMaterialResourcesDescriptorSet: SwDescriptorSet
    - mSceneMaterialResourcesDescriptorLayout: SwDescriptorLayout
    - mSceneVertexBuffer: SwAllocatedBuffer 
    - mSceneIndexBuffer: SwAllocatedBuffer 
    - mSceneNodeTransformsBuffer: SwAllocatedBuffer 
    - mSceneMaterialConstantsBuffer: SwAllocatedBuffer 
    - mSceneInstancesBuffer: SwAllocatedBuffer 
    - mSceneBoundsBuffer: SwAllocatedBuffer 
    - mSceneVisibleRenderInstancesInstanceIndexBuffer: SwAllocatedBuffer 
}

class SwAsset {
    {static} - sLatestAssetId: std::uint32_t = 0
    - mName: std::string
    - mId: std::uint32_t = 0
    - mDelete: bool = false
    - mReloadInstancesFlag: bool = true

    - mRawAsset: fastgltf::Asset 

    - mMeshes: std::vector<Mesh>
    {static} - mSamplers: std::unordered_map<vk::SamplerCreateInfo, SwSampler>
    - mImages: std::vector<SwAllocatedImage>
    - mMaterials: std::vector<SwMaterial>
    - mMaterialConstantsBuffer: SwAllocatedBuffer
    - mFirstMaterialInScene: std::uint32_t = 0

    - mTopNodes: std::vector<std::shared_ptr<Node>>
    - mNodes: std::vector<std::shared_ptr<Node>>
    - mNodeTransformsBuffer: SwAllocatedBuffer
    - mFirstNodeTransformInScene: std::uint32_t = 0

    - mInstances: std::vector<SwInstance> 
    - mInstancesBuffer: SwAllocatedBuffer
    - mFirstInstanceInScene: std::uint32_t = 0

    - mNumBounds: std::uint32_t
    - mBoundsBuffer: SwAllocatedBuffer
    - mFirstBoundInScene: std::uint32_t = 0
}

class SwInstance {
    {static} - sLatestInstanceId: std::uint32_t = 0
    - mAssetName: std::filesystem::path
    - mId: std::uint32_t
    - mDelete: bool
    - mData: SwInstanceData
}

struct SwVertex {
    + mPosition: glm::vec3
    + mNormal: glm::vec3
    + mColor: glm::vec4
    + mUv: glm::vec2
}

struct Bounds {
    + mMin: glm::vec3
    + mMax: glm::vec3
}

struct Primitive {
    + mRelativeFirstIndex: std::uint32_t
    + mIndexCount: std::uint32_t
    + mRelativeVertexOffset: std::uint32_t
    + mMaterial: SwMaterial&
}

class SwMesh {
    {static} - sLatestMeshId: std::uint32_t = 0
    - mName: std::string
    - mId: std::uint32_t
    - mPrimitives: std::vector<Primitive> 

    - Bounds mBounds
    - mRelativeFirstBounds: std::uint32_t

    - mVertexBuffer: SwAllocatedBuffer
    - mNumVertices: std::uint32_t = 0 
    - mVertexOffsetInScene: std::uint32_t = 0

    - mIndexBuffer: SwAllocatedBuffer
    - mNumIndices: std::uint32_t = 0 
    - mFirstIndexInScene: std::uint32_t = 0
}

class SwNode {
    - mName: std::string
    - mRelativeNodeIndex: std::uint32_t
    - mParent: std::weak_ptr<Node>
    - mChildren: std::vector<std::shared_ptr<Node>>
    - mLocalTransform: glm::mat4 
    - mWorldTransform: glm::mat4
}

class SwMeshNode {
    - Mesh* mMesh;
}

SwNode <|-- SwMeshNode

struct SwMaterialConstants {
    + mBaseFactor: glm::vec4
    + mEmissiveFactor: glm::vec4
    + mMetallicRoughnessFactor: glm::vec2
    + mNormalScale: float
    + mOcclusionStrength: float
}

struct SwMaterialResources {
    + mBase: SwMaterialImage
    + mMetallicRoughness: SwMaterialImage
    + mNormal: SwMaterialImage
    + mOcclusion: SwMaterialImage
    + mEmissive: SwMaterialImage
}

class SwMaterial {
    {static} - sLatestMaterialId: std::uint32_t = 0
    - mName: std::string
    - mRelativeMaterialIndex: std::uint32_t
    - mDoubleSided: bool
    - mAlphaMode: fastgltf::AlphaMode
    - mMaterialConstants: SwMaterialConstants
    - mMaterialResources: SwMaterialResources
    - mPipelineBundle: SwPipelineBundle
    - mConstantsBuffer: SwAllocatedBuffer&
    - mConstantsBufferOffset: std::uint32_t
    {static} - mMaterialPipelines: std::unordered_map<SwPipelineOptions, SwPipelinePipeline> 
    {static} - mOpaquePipelineLayout: SwPipelineLayout
    {static} - mTransparentPipelineLayout: SwPipelineLayout
}

struct SwRenderItem {
    + mIndexCount: std::uint32_t
    + mRenderInstanceCount: std::uint32_t
    + mFirstIndex: std::uint32_t
    + mVertexOffset: std::uint32_t
    + mFirstRenderInstance: std::uint32_t
    + mMaterialIndex: std::uint32_t
    + mNodeTransformIndex: std::uint32_t
    + mAssetIndex: std::uint32_t
    + mFirstInstance: std::uint32_t
    + mBoundsIndex: std::uint32_t
}

struct SwRenderInstance {
    + mRenderItemIndex: std::uint32_t
    + mSceneInstanceIndex: std::uint32_t
}

class SwBatch {
    {static} - mFirstRenderInstanceOffset: std::uint32_t
    - mPipelineBundle: SwPipelineBundle
    - mRenderItems: std::vector<SwRenderItem>
    - renderItemsStagingBuffer: SwStagingBuffer
    - preCullRenderItemsBuffer: SwAllocatedBuffer
    - postCullRenderItemsBuffer: SwAllocatedBuffer
    - postCullRenderItemsCountBuffer: SwAllocatedBuffer
    - mRenderInstance: std::vector<RenderInstance>
    - mRenderInstancesStagingBuffer: SwStagingBuffer
    - mRenderInstancesBuffer: SwAllocatedBuffer
}
@enduml 